/*----------------------------------------------------------
MASV: N18DCAT100
HO TEN: TRẦN QUỐC TRƯỢNG
LAB: 03
NGAY: 9/8/2021
----------------------------------------------------------*/
--i
CREATE PROC SP_INS_SINHVIEN @MASV NVARCHAR(20), @HOTEN NVARCHAR(100), @NGAYSINH DATETIME ,
							@DIACHI NVARCHAR(200), @MALOP VARCHAR(20), @TENDN NVARCHAR(100), 
							@MATKHAU NVARCHAR(50)
AS 
INSERT INTO SINHVIEN
VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, HASHBYTES('MD5', @MATKHAU))

GO

drop proc SP_INS_SINHVIEN

EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN VAN A', '1990-1-1', '280 AN DUONG VUONG', 'CNTT-K35', 'NVA', '123456'

SELECT * FROM SINHVIEN

--ii
CREATE SYMMETRIC KEY myKey_AES_256
WITH KEY_SOURCE = 'N18DCAT100',
ALGORITHM = AES_256
ENCRYPTION BY PASSWORD = '123456'
GO
SELECT * FROM sys.symmetric_keys

CREATE PROC SP_INS_NHANVIEN @MAVN VARCHAR(20), @HOTEN NVARCHAR(100), @EMAIL VARCHAR(20), @LUONG INT,
							@TENDN NVARCHAR(100), @MATKHAU NVARCHAR(100)
AS
	OPEN SYMMETRIC KEY myKey_AES_256 DECRYPTION BY PASSWORD = '123456'

	INSERT INTO NHANVIEN VALUES 
	(@MAVN, @HOTEN, @EMAIL, ENCRYPTBYKEY(Key_GUID('myKey_AES_256'), CONVERT(NVARCHAR, @LUONG)), 
	@TENDN, HASHBYTES('SHA1', @MATKHAU))

	CLOSE SYMMETRIC KEY myKey_AES_256
GO

DROP PROC SP_INS_NHANVIEN

EXEC SP_INS_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'

DELETE FROM NHANVIEN
SELECT * FROM NHANVIEN


--iii
CREATE PROC SP_SEL_NHANVIEN 
AS
	OPEN SYMMETRIC KEY myKey_AES_256 DECRYPTION BY PASSWORD = '123456'

	SELECT MANV, HOTEN, EMAIL, CONVERT(NVARCHAR, DECRYPTBYKEY(LUONG)) AS LUONGCB
	FROM NHANVIEN

	CLOSE SYMMETRIC KEY myKey_AES_256
GO

EXEC SP_SEL_NHANVIEN


