/*----------------------------------------------------------
MASV: N18DCAT100
HO TEN: TRẦN QUỐC TRƯỢNG
LAB: 03
NGAY: 9/8/2021
----------------------------------------------------------*/
CREATE TABLE SINHVIEN (
	MASV NVARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(256) NOT NULL
)

CREATE TABLE NHANVIEN (
	MAVN VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(256),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(256) NOT NULL
)

CREATE TABLE LOP (
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
)